name: cloudformation-deploy

run-name: cloudformation-deploy 

on: 
  push: 
    branches: 
      - main 

jobs: 
  deploy: 
    name: deploy cloudformation template 
    runs-on: ubuntu-latest
    steps: 
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: deploy
        run: aws cloudformation deploy --template-file ../../template.yaml --stack-name my-new-stack --parameter-overrides InstanceTypeParameter=t2.micro VolumeSize=20 VolumeType=gp3 SSHFromIP=186.121.35.177/32 HTTPFromIP=186.121.35.177/32 HTTPSFromIP=186.121.35.177/32
