name: cloudformation-deploy

run-name: cloudformation-deploy 

on: 
  push: 
    branches: 
      - main 


jobs: 
    deploy: 
        name: deploy cloudformation template 
        runs-on: ubuntu-latest
        steps: 
          - name: Configure aws credentials
            uses: aws-actions/configure-aws-credentials@v1
            with: 
              aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
              aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
              aws-region: ${{secrets.AWS_REGION}}

          - name: deploy
            run: aws cloudformation deploy --template-file /./template.yaml/template.json --stack-name my-new-stack --parameter-overrides Key1=Value1 Key2=Value2 --tags Key1=Value1 Key2=Value2

            