name: Lint CloudFormation Templates

on: [push]

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup cloud formation linter with latest version
        uses: scottbrenner/cfn-lint-action@v2

      - name: print the cloud formation linter version & run lister
        run: |
          cfn-lint --version
          cfn-lint -t ./main.yaml