name: CloudFormation nag

run-name: CloudFormation nag and linter for yaml

# Activación del workflow en push y pull request a la rama main
on: 
  push:
    branches:
      - main  # rama principal
  pull_request:
    branches:
      - main  # activación de workflow cada que se haga un PR a main

jobs: 
  cloudformation-nag:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Homebrew and install cfn-nag
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install ruby brew-gem
          brew gem install cfn-nag 

      - name: Run cfn-nag
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          cfn_nag_scan --input-path template.yaml

  cloudformation-linter:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup CloudFormation linter with latest version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the CloudFormation linter version & run linter
        run: |
          cfn-lint --version
          cfn-lint -t ./template.yaml
